### ISSUE TITLE
你不加磁力地址吗

### ISSUE THREAD

**Issue by Qa70601234** [luluxiaoyu/aria2tool#8]

**Comment by Qa70601234** [comment]
BT地址啊，这才能下bt

**Comment by luluxiaoyu** [comment]
忘了== 等我有空  
现在疫情被关在学校(

**Comment by luluxiaoyu** [comment]
或者你帮我改下配置 然后拉取合并吧 
https://github.com/luluxiaoyu/aria2tool/blob/master/res/aria2c/aria2.conf

**Comment by luluxiaoyu** [comment]
已修复 程序根目录删除aria2.conf即可重新下载
